# Generated by Django 3.2.5 on 2021-07-31 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_auto_20210731_0715"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeformula",
            old_name="amount",
            new_name="amount_per_recipe",
        ),
    ]
