# Generated by Django 3.2.5 on 2021-08-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_rename_amount_recipeformula_amount_per_recipe"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.CheckConstraint(
                check=models.Q(("cost_per_amount__gt", 0)),
                name="cost_per_amount_cannot_be_negative",
            ),
        ),
    ]
