# Generated by Django 3.2.5 on 2021-08-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0004_ingredient_cost_per_amount_cannot_be_negative"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)), name="amount_cannot_be_negative"
            ),
        ),
    ]
