# Generated by Django 3.2.5 on 2021-08-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0005_ingredient_amount_cannot_be_negative"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("article_number",), name="only_one_article_number"
            ),
        ),
    ]
