# Generated by Django 3.2.5 on 2021-08-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0007_auto_20210801_1641"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ingredient",
            name="only_unique_name",
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("name",), name="only_unique_ingredient_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.UniqueConstraint(
                fields=("name",), name="only_unique_recipe_name"
            ),
        ),
    ]
