# Generated by Django 3.2.5 on 2021-08-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0008_auto_20210801_1644"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ingredient",
            name="cost_per_amount_cannot_be_negative",
        ),
        migrations.RemoveConstraint(
            model_name="ingredient",
            name="amount_cannot_be_negative",
        ),
        migrations.RemoveConstraint(
            model_name="ingredient",
            name="only_unique_article_number",
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.CheckConstraint(
                check=models.Q(("cost_per_amount__gt", 0)),
                name="ingredient_cost_per_amount_cannot_be_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)),
                name="ingredient_amount_cannot_be_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("article_number",), name="only_unique_ingredient_article_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeformula",
            constraint=models.CheckConstraint(
                check=models.Q(("amount_per_recipe__gt", 0)),
                name="recipe_amount_cannot_be_negative",
            ),
        ),
    ]
